### ISSUE TITLE
git submodule update fails

### ISSUE THREAD

**Issue by SpaceCowboy850** [microsoft/Llama-2-Onnx#18]
I'm wondering if there is a problem with the way submodules are hooked up.

I'm trying to run the commands at the start, so specifically this:
git submodule init 7B_FT_float16
git submodule update

But when I go to update, a dialog opens up "Connect to Github".  I have tried to "sign in with code" and pass a personal access token with _all_ attributes checked.  I get a "Congratulations all set" on the webpage, but in the console, it continues as follows:

D:\github\llama2\ms_onnx>git submodule update
Cloning into 'D:/github/llama2/ms_onnx/7B_FT_float16'...
remote: Repository not found.
fatal: repository 'https://github.com/microsoft/Llama-2-Onnx-7-FT-16/' not found
fatal: clone of 'https://github.com/microsoft/Llama-2-Onnx-7-FT-16' into submodule path 'D:/github/llama2/ms_onnx/7B_FT_float16' failed
Failed to clone '7B_FT_float16'. Retry scheduled

I have tried this with 7B_FT_float32, 7B_float16 and 7B_float32, and they all have the same error.

Am I doing something wrong or is there something wrong with the submodules?

**Comment by JoshuaElsdon** [comment]
Hello, have you got access to the sub repositories? You can sign up here: https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR1sq8AbaR35DlqQqW8HAxY1UQlU4UThHTlFWVUUwMzBXV1gxWENRTjRHRi4u

This is discussed in the "before you start" section of the Readme. You can check if you have access by navigating to the sub repositories by clicking on them on the github.com UI, or navigating here: https://github.com/microsoft/Llama-2-Onnx-13-FT-16/tree/17171453f1a8093d1605c9bef8723693f6d97424 as an example. If you do not have access it will give you the 404 error.

Let me know if this is not the problem and I will dig deeper!

**Comment by SpaceCowboy850** [comment]
Sigh - reading failure on my end.  I've signed up and received access to these weights at least 2, maybe 3 times, I should have realized since it's Llama you have to do special sign up every time it's repackaged.

Just filled out the form and will await the results.

**Comment by tammanygrantmsft** [comment]
@SpaceCowboy850 looks like your access went through and now you're just "pending invite". I'm going to close this, but feel free to reopen if you have future access issues.

**Comment by mszhanyi** [comment]
<s>@tammanygrantmsft , how long does the process take? I submitted the request 3 days ago and it's still in process.</s>

It works now
